---
- name: yum install ntp 
  yum: name=ntp state=installed

- name: set ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644 backup=yes
  notify:
    - restart ntpd

- name: ntpd start and enable
  service: name=ntpd state=started enabled=yes
