---
- hosts: all
  become: yes

  roles:
    - { role: hostname, hostname: "{{ inventory_hostname }}" }
    - { role: locale, locale: "{{ base_locale }}" }
    - { role: keymap, keymap: "{{ base_keymap }}" }
    - { role: timezone, timezone: "{{ base_timezone }}" }
    - selinux/off
    - yum/update
    - { role: yum/install, packages: "{{ base_packages }}" }
