---
- name: new user
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    createhome: "{{ item.createhome }}"
    state: present
  with_items: "{{ add_users }}"
