---
- name: set docker.repo
  copy:
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo
    owner=root
    group=root
    mode=0644
    backup=yes

- name: install docker-engine
  yum:
    name=docker-engine
    state=installed

- name: docker start and enable
  service: name=docker state=started enabled=yes

- name: install docker-compose
  pip:
    name: docker-compose
